Rename variables and use bash syntax for if statements

diff --git a/x86_64/run b/x86_64/run
--- a/x86_64/run
+++ b/x86_64/run
@@ -52,6 +52,10 @@ if [[ -n $1 ]]; then
     echo "./${0##*/}: couldn't read \`$vm_dir_path\`: VM does not exist" >/dev/stderr
     exit 1
   fi
+  if [[ ! "$vm_dir_path" =~ ^[^/]+/[^/]+$ ]]; then
+    echo "ERROR: VM directory path incorrect format." >/dev/stderr
+    exit 1
+  fi
 else
   usage
   exit 1
